[libraries]
test-junit = "junit:junit:4.13.2"
test-strikt = "io.strikt:strikt-core:0.35.1"

[plugins]
kotlin = "org.jetbrains.kotlin.multiplatform:2.2.0"
dokka = "org.jetbrains.dokka:2.0.0"
nmcp = "com.gradleup.nmcp:1.2.0"
